### ISSUE TITLE
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by leowing** [LianjiaTech/gson-plugin#2]
```
> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> Affected Modules: app
```
使用 `classpath 'com.github.LianjiaTech:gson-plugin:2.0.1'` 后同步Gradle会出现上面的警告，希望能够解决。

**Comment by qq171161636** [comment]
这是你的AS的版本，改下依赖方式   上面说了

**Comment by Mrxxy** [comment]
把`compile`改成`implementation`或者`api`即可，建议多看官方文档，会有详细说明

**Comment by SmartDengg** [comment]
这个警告是由于 `gson.plugin` 内部使用了 `compile` 依赖：
[source code](https://github.com/LianjiaTech/gson-plugin/blob/master/gson_plugin/src/main/groovy/com/ke/gson/plugin/GsonPlugin.groovy#L22)
```groovy
 project.dependencies.add("compile", "com.github.LianjiaTech:gson-plugin-sdk:1.0.0")
```
我们将会在下个版本使用 `implementation` 替换，以消除警告。

**Comment by SmartDengg** [comment]
请使用最新版本 `classpath 'com.github.LianjiaTech:gson-plugin:2.1.0'`，我将关闭这个 issue，如果还有问题请再次打开它。

**Comment by leowing** [comment]
> 请使用最新版本 `classpath 'com.github.LianjiaTech:gson-plugin:2.1.0'`，我将关闭这个 issue，如果还有问题请再次打开它。

太棒了，这个问题解决了，多谢！
