### ISSUE TITLE
不支持在Library中引用该插件

### ISSUE THREAD

**Issue by BroganGrow** [LianjiaTech/gson-plugin#3]
组件化时需要加入到library中，但是会报错
```
ERROR: Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.
Affected Modules: checkstand
```

**Comment by tangfuling** [comment]
> 组件化时需要加入到library中，但是会报错
> 
> ```
> ERROR: Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.
> Affected Modules: checkstand
> ```

组件化场景下，library最终会跟host工程一起打包，所以只需要在host工程引用 apply plugin: 'com.ke.gson.plugin'，无需在library工程引用。
插件化场景下，各个插件是application模式，所以需要在插件中引用  apply plugin: 'com.ke.gson.plugin' 。
插件化场景下，如果插件对gson的引用采用compileOnly占位编译，则只需要在主工程引用。
